// ============================================================
// AnemiaCheck — Global TypeScript Types
// ============================================================

export type RiskLevel = 'low' | 'medium' | 'high';

export type QuestionType =
    | 'yes_no'
    | 'scale'
    | 'multiple_choice'
    | 'text'
    | 'number';

// ---- Assessment Session (unified photo + triage flow) -------
export interface AssessmentSession {
    sessionId: string; // generated by backend when image is uploaded
    imageUploaded: boolean;
    imageFile?: File;
    imagePreviewUrl?: string;
    answers: Answer[];
    result?: AssessmentResult;
}

// ---- Image Upload + Validation + Questions ------------------
// POST /api/assessment/start  multipart/form-data { image: File }
// Returns validation + generated questions in a single call
export interface ImageUploadResult {
    sessionId: string;
    imageValid: boolean;
    validationMessage: string;
    questions: Question[];
}

// ---- Questions (returned inline with upload) ----------------
export interface Question {
    id: string;
    type: QuestionType;
    text: string;
    options?: string[]; // for multiple_choice
    min?: number;       // for scale / number
    max?: number;       // for scale / number
    step?: number;      // for scale
    unit?: string;      // for number (e.g. "años")
    required?: boolean;
    hint?: string;      // optional helper text below question
}

export interface Answer {
    questionId: string;
    value: string | boolean | number | string[];
}

// ---- Final Assessment Result (image + triage combined) ------
// POST /api/assessment/submit  JSON { sessionId, answers: Answer[] }
// Returns: AssessmentResult
export interface AssessmentResult {
    riskLevel: RiskLevel;
    explanation: string;
    recommendations: string[];
}

// ---- Education Content --------------------------------------
// TODO: GET /api/education?riskLevel={level}
// Returns: EducationContent
export interface EducationSection {
    id: string;
    icon: string;
    title: string;
    content: string;
    riskLevels: RiskLevel[]; // which risk levels receive this content
}

export interface EducationContent {
    sections: EducationSection[];
}
